name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Set up cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/online-judge-tools
          .verify-helper/timestamps.remote.json
        key: verify-${{ github.run_number }}-${{ github.run_attempt }}
        restore-keys: verify-

    - name: Debug cache
      run: cat .verify-helper/timestamps.remote.json

    - name: Debug stupid shit
      run: git log -1 --date=iso --pretty="format:%ad" Makefile README.md

    - name: Debug stupid shit 2
      run: git log -1 --date=iso --pretty="format:%ad" Makefile

    - name: Debug stupid shit 3
      run: git log -1 --date=iso --pretty="format:%ad" -- Makefile

    - name: Run tests
      env:
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: oj-verify run
