name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cache/online-judge-tools
          .verify-helper/timestamps.remote.json
        key: verify-cache

    - name: Run tests
      env:
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: oj-verify run

    - name: Save cache
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.cache/online-judge-tools
          .verify-helper/timestamps.remote.json
        key: verify-cache
